// api generated by default when we use 'jaxrsinterfaces'
new File(basedir, "target/generated-sources/java/de/zalando/api/ApiException.java" ).exists();
new File(basedir, "target/generated-sources/java/de/zalando/api/ApiOriginFilter.java" ).exists();
new File(basedir, "target/generated-sources/java/de/zalando/api/ApiResponseMessage.java" ).exists();
new File(basedir, "target/generated-sources/java/de/zalando/api/NotFoundException.java" ).exists();

// real api from swagger-file
new File(basedir, "target/generated-sources/java/de/zalando/api/ApplicationsApi.java" ).exists();

// model
new File(basedir, "target/generated-sources/java/de/zalando/model/Application.java" ).exists();
new File(basedir, "target/generated-sources/java/de/zalando/model/ApplicationDetails.java" ).exists();
new File(basedir, "target/generated-sources/java/de/zalando/model/ApplicationSummary.java" ).exists();
new File(basedir, "target/generated-sources/java/de/zalando/model/Error.java" ).exists();