// api generated by default when we use 'jaxrsinterfaces'
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/EventTypesApi.java" ).exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/MetricsApi.java" ).exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/RegistryApi.java" ).exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiException.java" ).exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiOriginFilter.java" ).exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiResponseMessage.java" ).exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/NotFoundException.java" ).exists();

// model
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/BatchItemResponse.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/BusinessEvent.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Cursor.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/DataChangeEvent.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/DataChangeEventQualifier.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Event.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/EventMetadata.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/EventMetadataMetadata.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/EventStreamBatch.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/EventType.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/EventTypeSchema.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/EventTypeStatistics.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Metrics.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Partition.java").exists();
//new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Problem.java").exists();