// api generated by default when we use 'jaxrsinterfaces'
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiException.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiOriginFilter.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiResponseMessage.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/NotFoundException.java" ).exists();

// real api from swagger-file
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApplicationsApi.java" ).exists();

// model
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Application.javaDTO" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ApplicationDetailsDTO.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ApplicationSummaryDTO.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ErrorDTO.java" ).exists();