// api generated by default when we use 'jaxrsinterfaces'
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiException.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiOriginFilter.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApiResponseMessage.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/NotFoundException.java" ).exists();

// real api from swagger-file
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/api/ApplicationsApi.java" ).exists();

// model
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Application.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ApplicationDetails.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ApplicationSummary.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/Error.java" ).exists();

// builder
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ApplicationBuilder.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ApplicationDetailsBuider.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ApplicationSummaryBuilder.java" ).exists();
new File(basedir, "target/generated-sources/swagger-codegen/de/zalando/model/ErrorBuilder.java" ).exists();